-- Federations (shared ban lists) and per-chat admin log channels.
-- These tables are new; do not edit this file after it has been applied.

CREATE TABLE IF NOT EXISTS federations (
    id BIGSERIAL PRIMARY KEY,
    fed_id VARCHAR(36) NOT NULL,
    owner_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    require_reason BOOLEAN NOT NULL DEFAULT FALSE,
    notify_owner BOOLEAN NOT NULL DEFAULT TRUE,
    log_chat_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_federations_fed_id ON federations (fed_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_federations_owner_id ON federations (owner_id);

CREATE TABLE IF NOT EXISTS federation_admins (
    id BIGSERIAL PRIMARY KEY,
    fed_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fed_admins_fed_user ON federation_admins (fed_id, user_id);
CREATE INDEX IF NOT EXISTS idx_federation_admins_fed_id ON federation_admins (fed_id);

CREATE TABLE IF NOT EXISTS federation_chats (
    id BIGSERIAL PRIMARY KEY,
    fed_id VARCHAR(36) NOT NULL,
    chat_id BIGINT NOT NULL,
    quiet BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_federation_chats_chat_id ON federation_chats (chat_id);
CREATE INDEX IF NOT EXISTS idx_federation_chats_fed_id ON federation_chats (fed_id);

CREATE TABLE IF NOT EXISTS federation_bans (
    id BIGSERIAL PRIMARY KEY,
    fed_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    banned_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fed_bans_fed_user ON federation_bans (fed_id, user_id);
CREATE INDEX IF NOT EXISTS idx_federation_bans_fed_id ON federation_bans (fed_id);
CREATE INDEX IF NOT EXISTS idx_federation_bans_user_id ON federation_bans (user_id);

CREATE TABLE IF NOT EXISTS federation_subs (
    id BIGSERIAL PRIMARY KEY,
    fed_id VARCHAR(36) NOT NULL,
    subscribed_fed_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fed_subs_pair ON federation_subs (fed_id, subscribed_fed_id);
CREATE INDEX IF NOT EXISTS idx_federation_subs_fed_id ON federation_subs (fed_id);

CREATE TABLE IF NOT EXISTS log_channels (
    id BIGSERIAL PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    log_channel_id BIGINT NOT NULL,
    cat_settings BOOLEAN NOT NULL DEFAULT TRUE,
    cat_admin BOOLEAN NOT NULL DEFAULT TRUE,
    cat_user BOOLEAN NOT NULL DEFAULT TRUE,
    cat_automated BOOLEAN NOT NULL DEFAULT TRUE,
    cat_reports BOOLEAN NOT NULL DEFAULT TRUE,
    cat_other BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_log_channels_chat_id ON log_channels (chat_id);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users') THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'fk_federations_owner'
        ) THEN
            ALTER TABLE federations
            ADD CONSTRAINT fk_federations_owner
            FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'fk_federation_admins_user'
        ) THEN
            ALTER TABLE federation_admins
            ADD CONSTRAINT fk_federation_admins_user
            FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'fk_federation_bans_user'
        ) THEN
            ALTER TABLE federation_bans
            ADD CONSTRAINT fk_federation_bans_user
            FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'chats') THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'fk_federation_chats_chat'
        ) THEN
            ALTER TABLE federation_chats
            ADD CONSTRAINT fk_federation_chats_chat
            FOREIGN KEY (chat_id) REFERENCES chats(chat_id) ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'fk_log_channels_chat'
        ) THEN
            ALTER TABLE log_channels
            ADD CONSTRAINT fk_log_channels_chat
            FOREIGN KEY (chat_id) REFERENCES chats(chat_id) ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_federation_admins_fed'
    ) THEN
        ALTER TABLE federation_admins
        ADD CONSTRAINT fk_federation_admins_fed
        FOREIGN KEY (fed_id) REFERENCES federations(fed_id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_federation_chats_fed'
    ) THEN
        ALTER TABLE federation_chats
        ADD CONSTRAINT fk_federation_chats_fed
        FOREIGN KEY (fed_id) REFERENCES federations(fed_id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_federation_bans_fed'
    ) THEN
        ALTER TABLE federation_bans
        ADD CONSTRAINT fk_federation_bans_fed
        FOREIGN KEY (fed_id) REFERENCES federations(fed_id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_federation_subs_fed'
    ) THEN
        ALTER TABLE federation_subs
        ADD CONSTRAINT fk_federation_subs_fed
        FOREIGN KEY (fed_id) REFERENCES federations(fed_id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_federation_subs_target'
    ) THEN
        ALTER TABLE federation_subs
        ADD CONSTRAINT fk_federation_subs_target
        FOREIGN KEY (subscribed_fed_id) REFERENCES federations(fed_id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
END $$;
